package com.mkyong.helloworld.entity;
// Generated Jan 28, 2017 6:19:52 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * MBusho generated by hbm2java
 */
@Entity
@Table(name = "m_busho", catalog = "spring")
public class MBusho implements java.io.Serializable {

	private String code;
	private int version;
	private String name;
	private Set<MKokyakuKojin> MKokyakuKojins = new HashSet<MKokyakuKojin>(0);
	private Set<MKokyaku> MKokyakus = new HashSet<MKokyaku>(0);
	private Set<MShain> MShains = new HashSet<MShain>(0);
	private Set<MKokyakuBusho> MKokyakuBushos = new HashSet<MKokyakuBusho>(0);

	public MBusho() {
	}

	public MBusho(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public MBusho(String code, String name, Set<MKokyakuKojin> MKokyakuKojins, Set<MKokyaku> MKokyakus,
			Set<MShain> MShains, Set<MKokyakuBusho> MKokyakuBushos) {
		this.code = code;
		this.name = name;
		this.MKokyakuKojins = MKokyakuKojins;
		this.MKokyakus = MKokyakus;
		this.MShains = MShains;
		this.MKokyakuBushos = MKokyakuBushos;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MBusho")
	public Set<MKokyakuKojin> getMKokyakuKojins() {
		return this.MKokyakuKojins;
	}

	public void setMKokyakuKojins(Set<MKokyakuKojin> MKokyakuKojins) {
		this.MKokyakuKojins = MKokyakuKojins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MBusho")
	public Set<MKokyaku> getMKokyakus() {
		return this.MKokyakus;
	}

	public void setMKokyakus(Set<MKokyaku> MKokyakus) {
		this.MKokyakus = MKokyakus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MBusho")
	public Set<MShain> getMShains() {
		return this.MShains;
	}

	public void setMShains(Set<MShain> MShains) {
		this.MShains = MShains;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MBusho")
	public Set<MKokyakuBusho> getMKokyakuBushos() {
		return this.MKokyakuBushos;
	}

	public void setMKokyakuBushos(Set<MKokyakuBusho> MKokyakuBushos) {
		this.MKokyakuBushos = MKokyakuBushos;
	}

}
