package com.mkyong.helloworld.entity;
// Generated Jan 28, 2017 1:40:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MBusho generated by hbm2java
 */
@Entity
@Table(name = "m_busho", catalog = "spring", uniqueConstraints = @UniqueConstraint(columnNames = "record_id"))
public class MBusho implements java.io.Serializable {

	private String code;
	private int version;
	private String name;
	private int recordId;
	private Set<MKokyaku> MKokyakus = new HashSet<MKokyaku>(0);
	private Set<MShain> MShains = new HashSet<MShain>(0);
	private Set<MKokyakuBusho> MKokyakuBushos = new HashSet<MKokyakuBusho>(0);

	public MBusho() {
	}

	public MBusho(String name, int recordId) {
		this.name = name;
		this.recordId = recordId;
	}

	public MBusho(String name, int recordId, Set<MKokyaku> MKokyakus, Set<MShain> MShains,
			Set<MKokyakuBusho> MKokyakuBushos) {
		this.name = name;
		this.recordId = recordId;
		this.MKokyakus = MKokyakus;
		this.MShains = MShains;
		this.MKokyakuBushos = MKokyakuBushos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "code", unique = true, nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "record_id", unique = true, nullable = false)
	public int getRecordId() {
		return this.recordId;
	}

	public void setRecordId(int recordId) {
		this.recordId = recordId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MBusho")
	public Set<MKokyaku> getMKokyakus() {
		return this.MKokyakus;
	}

	public void setMKokyakus(Set<MKokyaku> MKokyakus) {
		this.MKokyakus = MKokyakus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MBusho")
	public Set<MShain> getMShains() {
		return this.MShains;
	}

	public void setMShains(Set<MShain> MShains) {
		this.MShains = MShains;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MBusho")
	public Set<MKokyakuBusho> getMKokyakuBushos() {
		return this.MKokyakuBushos;
	}

	public void setMKokyakuBushos(Set<MKokyakuBusho> MKokyakuBushos) {
		this.MKokyakuBushos = MKokyakuBushos;
	}

}
