package com.mkyong.helloworld.entity;
// Generated Jan 28, 2017 1:40:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MKokyakuBushoId generated by hbm2java
 */
@Embeddable
public class MKokyakuBushoId implements java.io.Serializable {

	private int kokyakuId;
	private int bushoId;

	public MKokyakuBushoId() {
	}

	public MKokyakuBushoId(int kokyakuId, int bushoId) {
		this.kokyakuId = kokyakuId;
		this.bushoId = bushoId;
	}

	@Column(name = "kokyaku_id", nullable = false)
	public int getKokyakuId() {
		return this.kokyakuId;
	}

	public void setKokyakuId(int kokyakuId) {
		this.kokyakuId = kokyakuId;
	}

	@Column(name = "busho_id", nullable = false)
	public int getBushoId() {
		return this.bushoId;
	}

	public void setBushoId(int bushoId) {
		this.bushoId = bushoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MKokyakuBushoId))
			return false;
		MKokyakuBushoId castOther = (MKokyakuBushoId) other;

		return (this.getKokyakuId() == castOther.getKokyakuId()) && (this.getBushoId() == castOther.getBushoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getKokyakuId();
		result = 37 * result + this.getBushoId();
		return result;
	}

}
