package com.mkyong.helloworld.entity;
// Generated Jan 28, 2017 1:11:14 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MKokyaku generated by hbm2java
 */
@Entity
@Table(name = "m_kokyaku", catalog = "spring", uniqueConstraints = @UniqueConstraint(columnNames = "record_id"))
public class MKokyaku implements java.io.Serializable {

	private String code;
	private int version;
	private KbKokyaku kbKokyaku;
	private KbKokyakuGentei kbKokyakuGentei;
	private MBusho MBusho;
	private String name;
	private String address;
	private int recordId;
	private Set<MKokyakuBusho> MKokyakuBushos = new HashSet<MKokyakuBusho>(0);
	private Set<MKokyakuKojin> MKokyakuKojinsForOyaKokyakuId = new HashSet<MKokyakuKojin>(0);
	private Set<MKokyakuKojin> MKokyakuKojinsForKokyakuId = new HashSet<MKokyakuKojin>(0);

	public MKokyaku() {
	}

	public MKokyaku(KbKokyaku kbKokyaku, KbKokyakuGentei kbKokyakuGentei, MBusho MBusho, String name, String address,
			int recordId) {
		this.kbKokyaku = kbKokyaku;
		this.kbKokyakuGentei = kbKokyakuGentei;
		this.MBusho = MBusho;
		this.name = name;
		this.address = address;
		this.recordId = recordId;
	}

	public MKokyaku(KbKokyaku kbKokyaku, KbKokyakuGentei kbKokyakuGentei, MBusho MBusho, String name, String address,
			int recordId, Set<MKokyakuBusho> MKokyakuBushos, Set<MKokyakuKojin> MKokyakuKojinsForOyaKokyakuId,
			Set<MKokyakuKojin> MKokyakuKojinsForKokyakuId) {
		this.kbKokyaku = kbKokyaku;
		this.kbKokyakuGentei = kbKokyakuGentei;
		this.MBusho = MBusho;
		this.name = name;
		this.address = address;
		this.recordId = recordId;
		this.MKokyakuBushos = MKokyakuBushos;
		this.MKokyakuKojinsForOyaKokyakuId = MKokyakuKojinsForOyaKokyakuId;
		this.MKokyakuKojinsForKokyakuId = MKokyakuKojinsForKokyakuId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "code", unique = true, nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kokyaku_kubun", nullable = false)
	public KbKokyaku getKbKokyaku() {
		return this.kbKokyaku;
	}

	public void setKbKokyaku(KbKokyaku kbKokyaku) {
		this.kbKokyaku = kbKokyaku;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gentei_kubun", nullable = false)
	public KbKokyakuGentei getKbKokyakuGentei() {
		return this.kbKokyakuGentei;
	}

	public void setKbKokyakuGentei(KbKokyakuGentei kbKokyakuGentei) {
		this.kbKokyakuGentei = kbKokyakuGentei;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shukan_busho_id", nullable = false)
	public MBusho getMBusho() {
		return this.MBusho;
	}

	public void setMBusho(MBusho MBusho) {
		this.MBusho = MBusho;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "record_id", unique = true, nullable = false)
	public int getRecordId() {
		return this.recordId;
	}

	public void setRecordId(int recordId) {
		this.recordId = recordId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MKokyaku")
	public Set<MKokyakuBusho> getMKokyakuBushos() {
		return this.MKokyakuBushos;
	}

	public void setMKokyakuBushos(Set<MKokyakuBusho> MKokyakuBushos) {
		this.MKokyakuBushos = MKokyakuBushos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MKokyakuByOyaKokyakuId")
	public Set<MKokyakuKojin> getMKokyakuKojinsForOyaKokyakuId() {
		return this.MKokyakuKojinsForOyaKokyakuId;
	}

	public void setMKokyakuKojinsForOyaKokyakuId(Set<MKokyakuKojin> MKokyakuKojinsForOyaKokyakuId) {
		this.MKokyakuKojinsForOyaKokyakuId = MKokyakuKojinsForOyaKokyakuId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MKokyakuByKokyakuId")
	public Set<MKokyakuKojin> getMKokyakuKojinsForKokyakuId() {
		return this.MKokyakuKojinsForKokyakuId;
	}

	public void setMKokyakuKojinsForKokyakuId(Set<MKokyakuKojin> MKokyakuKojinsForKokyakuId) {
		this.MKokyakuKojinsForKokyakuId = MKokyakuKojinsForKokyakuId;
	}

}
