package com.mkyong.helloworld.entity;
// Generated Mar 19, 2017 11:27:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * MKokyakuTantoBushoRental generated by hbm2java
 */
@Entity
@Table(name = "m_kokyaku_tanto_busho_rental", catalog = "spring")
public class MKokyakuTantoBushoRental implements java.io.Serializable {

	private MKokyakuTantoBushoRentalId id;
	private int version;
	private MKokyakuTantoBusho MKokyakuTantoBusho;
	private String courseCode;

	public MKokyakuTantoBushoRental() {
	}

	public MKokyakuTantoBushoRental(MKokyakuTantoBusho MKokyakuTantoBusho, String courseCode) {
		this.MKokyakuTantoBusho = MKokyakuTantoBusho;
		this.courseCode = courseCode;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "kokyakuCode", column = @Column(name = "kokyaku_code", nullable = false)),
			@AttributeOverride(name = "bushoCode", column = @Column(name = "busho_code", nullable = false)) })
	public MKokyakuTantoBushoRentalId getId() {
		return this.id;
	}

	public void setId(MKokyakuTantoBushoRentalId id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public MKokyakuTantoBusho getMKokyakuTantoBusho() {
		return this.MKokyakuTantoBusho;
	}

	public void setMKokyakuTantoBusho(MKokyakuTantoBusho MKokyakuTantoBusho) {
		this.MKokyakuTantoBusho = MKokyakuTantoBusho;
	}

	@Column(name = "course_code", nullable = false, length = 2)
	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

}
