package com.mkyong.helloworld.entity;
// Generated Jan 28, 2017 1:40:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MKokyakuKojin generated by hbm2java
 */
@Entity
@Table(name = "m_kokyaku_kojin", catalog = "spring", uniqueConstraints = @UniqueConstraint(columnNames = "record_id"))
public class MKokyakuKojin implements java.io.Serializable {

	private Integer kokyakuId;
	private int version;
	private MKokyaku MKokyakuByOyaKokyakuId;
	private MKokyaku MKokyakuByKokyakuId;
	private int recordId;

	public MKokyakuKojin() {
	}

	public MKokyakuKojin(MKokyaku MKokyakuByOyaKokyakuId, MKokyaku MKokyakuByKokyakuId, int recordId) {
		this.MKokyakuByOyaKokyakuId = MKokyakuByOyaKokyakuId;
		this.MKokyakuByKokyakuId = MKokyakuByKokyakuId;
		this.recordId = recordId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "kokyaku_id", unique = true, nullable = false)
	public Integer getKokyakuId() {
		return this.kokyakuId;
	}

	public void setKokyakuId(Integer kokyakuId) {
		this.kokyakuId = kokyakuId;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oya_kokyaku_id", nullable = false)
	public MKokyaku getMKokyakuByOyaKokyakuId() {
		return this.MKokyakuByOyaKokyakuId;
	}

	public void setMKokyakuByOyaKokyakuId(MKokyaku MKokyakuByOyaKokyakuId) {
		this.MKokyakuByOyaKokyakuId = MKokyakuByOyaKokyakuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kokyaku_id", unique = true, nullable = false, insertable = false, updatable = false)
	public MKokyaku getMKokyakuByKokyakuId() {
		return this.MKokyakuByKokyakuId;
	}

	public void setMKokyakuByKokyakuId(MKokyaku MKokyakuByKokyakuId) {
		this.MKokyakuByKokyakuId = MKokyakuByKokyakuId;
	}

	@Column(name = "record_id", unique = true, nullable = false)
	public int getRecordId() {
		return this.recordId;
	}

	public void setRecordId(int recordId) {
		this.recordId = recordId;
	}

}
