package com.mkyong.helloworld.entity;
// Generated Jan 28, 2017 6:19:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * MKokyakuKojin generated by hbm2java
 */
@Entity
@Table(name = "m_kokyaku_kojin", catalog = "spring")
public class MKokyakuKojin implements java.io.Serializable {

	private String kokyakuCode;
	private int version;
	private MBusho MBusho;
	private MKokyaku MKokyaku;

	public MKokyakuKojin() {
	}

	public MKokyakuKojin(String kokyakuCode, MBusho MBusho, MKokyaku MKokyaku) {
		this.kokyakuCode = kokyakuCode;
		this.MBusho = MBusho;
		this.MKokyaku = MKokyaku;
	}

	@Id

	@Column(name = "kokyaku_code", unique = true, nullable = false)
	public String getKokyakuCode() {
		return this.kokyakuCode;
	}

	public void setKokyakuCode(String kokyakuCode) {
		this.kokyakuCode = kokyakuCode;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kokyaku_code", unique = true, nullable = false, insertable = false, updatable = false)
	public MBusho getMBusho() {
		return this.MBusho;
	}

	public void setMBusho(MBusho MBusho) {
		this.MBusho = MBusho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oya_kokyaku_code", nullable = false)
	public MKokyaku getMKokyaku() {
		return this.MKokyaku;
	}

	public void setMKokyaku(MKokyaku MKokyaku) {
		this.MKokyaku = MKokyaku;
	}

}
