package com.mkyong.helloworld.entity;
// Generated Mar 19, 2017 11:27:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * MKokyakuTantoBusho generated by hbm2java
 */
@Entity
@Table(name = "m_kokyaku_tanto_busho", catalog = "spring")
public class MKokyakuTantoBusho extends AbstractEntity implements java.io.Serializable {

	private MKokyakuTantoBushoId id;
	private int version;
	private MBusho MBusho;
	private MKokyaku MKokyaku;
	private MNyukinMoto MNyukinMoto;
	private MSeikyuSaki MSeikyuSaki;
	private String shohizeiKubun;
	private String sekininshaName;
	private MKokyakuTantoBushoHanbai MKokyakuTantoBushoHanbai;
	private MKokyakuTantoBushoRental MKokyakuTantoBushoRental;

	public MKokyakuTantoBusho() {
	}

	public MKokyakuTantoBusho(MKokyakuTantoBushoId id, MBusho MBusho, MKokyaku MKokyaku, MNyukinMoto MNyukinMoto,
			MSeikyuSaki MSeikyuSaki, String shohizeiKubun, String sekininshaName) {
		this.id = id;
		this.MBusho = MBusho;
		this.MKokyaku = MKokyaku;
		this.MNyukinMoto = MNyukinMoto;
		this.MSeikyuSaki = MSeikyuSaki;
		this.shohizeiKubun = shohizeiKubun;
		this.sekininshaName = sekininshaName;
	}

	public MKokyakuTantoBusho(MKokyakuTantoBushoId id, MBusho MBusho, MKokyaku MKokyaku, MNyukinMoto MNyukinMoto,
			MSeikyuSaki MSeikyuSaki, String shohizeiKubun, String sekininshaName,
			MKokyakuTantoBushoHanbai MKokyakuTantoBushoHanbai, MKokyakuTantoBushoRental MKokyakuTantoBushoRental) {
		this.id = id;
		this.MBusho = MBusho;
		this.MKokyaku = MKokyaku;
		this.MNyukinMoto = MNyukinMoto;
		this.MSeikyuSaki = MSeikyuSaki;
		this.shohizeiKubun = shohizeiKubun;
		this.sekininshaName = sekininshaName;
		this.MKokyakuTantoBushoHanbai = MKokyakuTantoBushoHanbai;
		this.MKokyakuTantoBushoRental = MKokyakuTantoBushoRental;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "kokyakuCode", column = @Column(name = "kokyaku_code", nullable = false)),
			@AttributeOverride(name = "bushoCode", column = @Column(name = "busho_code", nullable = false)) })
	public MKokyakuTantoBushoId getId() {
		return this.id;
	}

	public void setId(MKokyakuTantoBushoId id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "busho_code", nullable = false, insertable = false, updatable = false)
	public MBusho getMBusho() {
		return this.MBusho;
	}

	public void setMBusho(MBusho MBusho) {
		this.MBusho = MBusho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kokyaku_code", nullable = false, insertable = false, updatable = false)
	public MKokyaku getMKokyaku() {
		return this.MKokyaku;
	}

	public void setMKokyaku(MKokyaku MKokyaku) {
		this.MKokyaku = MKokyaku;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nyukin_moto_id", nullable = false)
	public MNyukinMoto getMNyukinMoto() {
		return this.MNyukinMoto;
	}

	public void setMNyukinMoto(MNyukinMoto MNyukinMoto) {
		this.MNyukinMoto = MNyukinMoto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seikyu_saki_id", nullable = false)
	public MSeikyuSaki getMSeikyuSaki() {
		return this.MSeikyuSaki;
	}

	public void setMSeikyuSaki(MSeikyuSaki MSeikyuSaki) {
		this.MSeikyuSaki = MSeikyuSaki;
	}

	@Column(name = "shohizei_kubun", nullable = false)
	public String getShohizeiKubun() {
		return this.shohizeiKubun;
	}

	public void setShohizeiKubun(String shohizeiKubun) {
		this.shohizeiKubun = shohizeiKubun;
	}

	@Column(name = "sekininsha_name", nullable = false)
	public String getSekininshaName() {
		return this.sekininshaName;
	}

	public void setSekininshaName(String sekininshaName) {
		this.sekininshaName = sekininshaName;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "MKokyakuTantoBusho")
	public MKokyakuTantoBushoHanbai getMKokyakuTantoBushoHanbai() {
		return this.MKokyakuTantoBushoHanbai;
	}

	public void setMKokyakuTantoBushoHanbai(MKokyakuTantoBushoHanbai MKokyakuTantoBushoHanbai) {
		this.MKokyakuTantoBushoHanbai = MKokyakuTantoBushoHanbai;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "MKokyakuTantoBusho")
	public MKokyakuTantoBushoRental getMKokyakuTantoBushoRental() {
		return this.MKokyakuTantoBushoRental;
	}

	public void setMKokyakuTantoBushoRental(MKokyakuTantoBushoRental MKokyakuTantoBushoRental) {
		this.MKokyakuTantoBushoRental = MKokyakuTantoBushoRental;
	}

}
