package com.mkyong.helloworld.entity;
// Generated Jan 28, 2017 6:19:52 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * MKokyaku generated by hbm2java
 */
@Entity
@Table(name = "m_kokyaku", catalog = "spring")
public class MKokyaku implements java.io.Serializable {

	private String code;
	private int version;
	private MBusho MBusho;
	private String name;
	private String address;
	private String kokyakuKubun;
	private String genteiKubun;
	private Set<MKokyakuBusho> MKokyakuBushos = new HashSet<MKokyakuBusho>(0);
	private Set<MKokyakuKojin> MKokyakuKojins = new HashSet<MKokyakuKojin>(0);

	public MKokyaku() {
	}

	public MKokyaku(String code, MBusho MBusho, String name, String address, String kokyakuKubun, String genteiKubun) {
		this.code = code;
		this.MBusho = MBusho;
		this.name = name;
		this.address = address;
		this.kokyakuKubun = kokyakuKubun;
		this.genteiKubun = genteiKubun;
	}

	public MKokyaku(String code, MBusho MBusho, String name, String address, String kokyakuKubun, String genteiKubun,
			Set<MKokyakuBusho> MKokyakuBushos, Set<MKokyakuKojin> MKokyakuKojins) {
		this.code = code;
		this.MBusho = MBusho;
		this.name = name;
		this.address = address;
		this.kokyakuKubun = kokyakuKubun;
		this.genteiKubun = genteiKubun;
		this.MKokyakuBushos = MKokyakuBushos;
		this.MKokyakuKojins = MKokyakuKojins;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shukan_busho_code", nullable = false)
	public MBusho getMBusho() {
		return this.MBusho;
	}

	public void setMBusho(MBusho MBusho) {
		this.MBusho = MBusho;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "kokyaku_kubun", nullable = false)
	public String getKokyakuKubun() {
		return this.kokyakuKubun;
	}

	public void setKokyakuKubun(String kokyakuKubun) {
		this.kokyakuKubun = kokyakuKubun;
	}

	@Column(name = "gentei_kubun", nullable = false)
	public String getGenteiKubun() {
		return this.genteiKubun;
	}

	public void setGenteiKubun(String genteiKubun) {
		this.genteiKubun = genteiKubun;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MKokyaku")
	public Set<MKokyakuBusho> getMKokyakuBushos() {
		return this.MKokyakuBushos;
	}

	public void setMKokyakuBushos(Set<MKokyakuBusho> MKokyakuBushos) {
		this.MKokyakuBushos = MKokyakuBushos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MKokyaku")
	public Set<MKokyakuKojin> getMKokyakuKojins() {
		return this.MKokyakuKojins;
	}

	public void setMKokyakuKojins(Set<MKokyakuKojin> MKokyakuKojins) {
		this.MKokyakuKojins = MKokyakuKojins;
	}

}
