package com.mkyong.helloworld.entity;
// Generated Jan 28, 2017 1:11:14 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MKokyakuBusho generated by hbm2java
 */
@Entity
@Table(name = "m_kokyaku_busho", catalog = "spring", uniqueConstraints = @UniqueConstraint(columnNames = "record_id"))
public class MKokyakuBusho implements java.io.Serializable {

	private MKokyakuBushoId id;
	private int version;
	private MBusho MBusho;
	private MKokyaku MKokyaku;
	private MShain MShain;
	private String sekininsha;
	private int recordId;

	public MKokyakuBusho() {
	}

	public MKokyakuBusho(MKokyakuBushoId id, MBusho MBusho, MKokyaku MKokyaku, MShain MShain, String sekininsha,
			int recordId) {
		this.id = id;
		this.MBusho = MBusho;
		this.MKokyaku = MKokyaku;
		this.MShain = MShain;
		this.sekininsha = sekininsha;
		this.recordId = recordId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "kokyakuId", column = @Column(name = "kokyaku_id", nullable = false)),
			@AttributeOverride(name = "bushoId", column = @Column(name = "busho_id", nullable = false)) })
	public MKokyakuBushoId getId() {
		return this.id;
	}

	public void setId(MKokyakuBushoId id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "busho_id", nullable = false, insertable = false, updatable = false)
	public MBusho getMBusho() {
		return this.MBusho;
	}

	public void setMBusho(MBusho MBusho) {
		this.MBusho = MBusho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kokyaku_id", nullable = false, insertable = false, updatable = false)
	public MKokyaku getMKokyaku() {
		return this.MKokyaku;
	}

	public void setMKokyaku(MKokyaku MKokyaku) {
		this.MKokyaku = MKokyaku;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tanto_shain_id", nullable = false)
	public MShain getMShain() {
		return this.MShain;
	}

	public void setMShain(MShain MShain) {
		this.MShain = MShain;
	}

	@Column(name = "sekininsha", nullable = false)
	public String getSekininsha() {
		return this.sekininsha;
	}

	public void setSekininsha(String sekininsha) {
		this.sekininsha = sekininsha;
	}

	@Column(name = "record_id", unique = true, nullable = false)
	public int getRecordId() {
		return this.recordId;
	}

	public void setRecordId(int recordId) {
		this.recordId = recordId;
	}

}
