package com.mkyong.helloworld.entity;
// Generated Mar 19, 2017 11:27:00 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * MNyukinMoto generated by hbm2java
 */
@Entity
@Table(name = "m_nyukin_moto", catalog = "spring")
public class MNyukinMoto extends AbstractEntity implements java.io.Serializable {

	/**
	 * SID.
	 */
	private static final long serialVersionUID = 5718076066467915505L;

	private Integer id;
	private int version;
	private String hanbaiKubun;
	private MNyukinKakeInfo MNyukinKakeInfo;

	public MNyukinMoto() {
	}

	public MNyukinMoto(String hanbaiKubun) {
		this.hanbaiKubun = hanbaiKubun;
	}

	public MNyukinMoto(String hanbaiKubun, MNyukinKakeInfo MNyukinKakeInfo) {
		this.hanbaiKubun = hanbaiKubun;
		this.MNyukinKakeInfo = MNyukinKakeInfo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "hanbai_kubun", nullable = false)
	public String getHanbaiKubun() {
		return this.hanbaiKubun;
	}

	public void setHanbaiKubun(String hanbaiKubun) {
		this.hanbaiKubun = hanbaiKubun;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "MNyukinMoto")
	public MNyukinKakeInfo getMNyukinKakeInfo() {
		return this.MNyukinKakeInfo;
	}

	public void setMNyukinKakeInfo(MNyukinKakeInfo MNyukinKakeInfo) {
		this.MNyukinKakeInfo = MNyukinKakeInfo;
	}

}
