package com.mkyong.helloworld.entity;
// Generated Jan 28, 2017 1:40:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MShain generated by hbm2java
 */
@Entity
@Table(name = "m_shain", catalog = "spring", uniqueConstraints = @UniqueConstraint(columnNames = "record_id"))
public class MShain implements java.io.Serializable {

	private String code;
	private int version;
	private MBusho MBusho;
	private String name;
	private int recordId;
	private Set<MKokyakuBusho> MKokyakuBushos = new HashSet<MKokyakuBusho>(0);

	public MShain() {
	}

	public MShain(MBusho MBusho, String name, int recordId) {
		this.MBusho = MBusho;
		this.name = name;
		this.recordId = recordId;
	}

	public MShain(MBusho MBusho, String name, int recordId, Set<MKokyakuBusho> MKokyakuBushos) {
		this.MBusho = MBusho;
		this.name = name;
		this.recordId = recordId;
		this.MKokyakuBushos = MKokyakuBushos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "code", unique = true, nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shozoku_busho_id", nullable = false)
	public MBusho getMBusho() {
		return this.MBusho;
	}

	public void setMBusho(MBusho MBusho) {
		this.MBusho = MBusho;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "record_id", unique = true, nullable = false)
	public int getRecordId() {
		return this.recordId;
	}

	public void setRecordId(int recordId) {
		this.recordId = recordId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MShain")
	public Set<MKokyakuBusho> getMKokyakuBushos() {
		return this.MKokyakuBushos;
	}

	public void setMKokyakuBushos(Set<MKokyakuBusho> MKokyakuBushos) {
		this.MKokyakuBushos = MKokyakuBushos;
	}

}
