package com.mkyong.helloworld.entity;
// Generated Jan 22, 2017 11:49:44 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Uriage generated by hbm2java
 */
@Entity
@Table(name = "uriage", catalog = "sakila", uniqueConstraints = @UniqueConstraint(columnNames = { "denpyo_no",
		"denpyo_no_edaban", "uriagebi", "denpyo_kubun" }))
public class Uriage implements java.io.Serializable {

	private String seq;
	private int version;
	private String denpyoNo;
	private String denpyoNoEdaban;
	private Date uriagebi;
	private String denpyoKubun;
	private long kigaku;
	private short customerId;

	public Uriage() {
	}

	public Uriage(String seq, String denpyoNo, String denpyoNoEdaban, Date uriagebi, String denpyoKubun, long kigaku,
			short customerId) {
		this.seq = seq;
		this.denpyoNo = denpyoNo;
		this.denpyoNoEdaban = denpyoNoEdaban;
		this.uriagebi = uriagebi;
		this.denpyoKubun = denpyoKubun;
		this.kigaku = kigaku;
		this.customerId = customerId;
	}

	@Id

	@Column(name = "seq", unique = true, nullable = false)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "denpyo_no", nullable = false)
	public String getDenpyoNo() {
		return this.denpyoNo;
	}

	public void setDenpyoNo(String denpyoNo) {
		this.denpyoNo = denpyoNo;
	}

	@Column(name = "denpyo_no_edaban", nullable = false)
	public String getDenpyoNoEdaban() {
		return this.denpyoNoEdaban;
	}

	public void setDenpyoNoEdaban(String denpyoNoEdaban) {
		this.denpyoNoEdaban = denpyoNoEdaban;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "uriagebi", nullable = false, length = 10)
	public Date getUriagebi() {
		return this.uriagebi;
	}

	public void setUriagebi(Date uriagebi) {
		this.uriagebi = uriagebi;
	}

	@Column(name = "denpyo_kubun", nullable = false)
	public String getDenpyoKubun() {
		return this.denpyoKubun;
	}

	public void setDenpyoKubun(String denpyoKubun) {
		this.denpyoKubun = denpyoKubun;
	}

	@Column(name = "kigaku", nullable = false, precision = 10, scale = 0)
	public long getKigaku() {
		return this.kigaku;
	}

	public void setKigaku(long kigaku) {
		this.kigaku = kigaku;
	}

	@Column(name = "customer_id", nullable = false)
	public short getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(short customerId) {
		this.customerId = customerId;
	}

}
